---
  - name: add default gateway for office2Server
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth0
      line: DEFROUTE=no

  - name: add default gateway for office2Server
    lineinfile:
      dest: /etc/sysconfig/network-scripts/ifcfg-eth1
      line: GATEWAY=192.168.1.129

  - name: Restart network
    systemd:
      name: network
      state: restarted
...
